version: '3.9'

services:
  minecraft:
    ports: # change the first port number -- this is your local machine port
      - ${MC_PORT}:25565
    volumes:
      - ${MC_PATH}:/data
    hostname: minecraft
    environment:
      EULA: "TRUE"
      MAX_MEMORY: ${MC_MAXMEMORY} # this option sets the RAM limit
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${MC_RCONPASS} # uses the password from the .env variables file
      RCON_PORT: 25575
    image: itzg/minecraft-server:latest
    restart: always
  rcon:
    image: itzg/rcon:latest
    ports:
      - ${RCON_WEBPORT}:4326 
      - ${RCON_SOCKETPORT}:4327
    volumes:
      - ${RCON_PATH}:/opt/rcon-web-admin/db
    environment:
      RWA_RCON_PORT: 25575
      RWA_USERNAME: ${RCON_USER}
      RWA_PASSWORD: ${RCON_PASS}
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: minecraft # if this does not work: docker network ls; then docker network inspect NAME, then read the ip-address
      RWA_RCON_PASSWORD: ${MC_RCONPASS}
      RWA_WEBSOCKET_URL: "ws://localhost:${RCON_SOCKETPORT}"