name: Ping the server stack
on: 
  push:
    paths:
    - '.env'
    - 'docker-compose.yml'
  pull_request:
    branches:
      - main

jobs:
  ping_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir /home/runner/mcserver
      - run: mkdir /home/runner/rcon
      - name: Build the stack
        run: docker-compose up -d
      - name: Sleep for 20 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: ping the Minecraft server
        run: nc -vz localhost 10001
      - name: ping the RCON web interface
        run: nc -vz localhost 11001
      - name: ping the RCON web socket
        run: nc -vz localhost 12001