name: Test server with docker compose
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list folders
        run: ls /home
      - name: create the folders
        run: mkdir /home/ubuntu/mcserver
      - run: mkdir /home/ubuntu/rcon
      - name: Build the stack
        run: docker-compose up -d
      - name: Test Minecraft server
        run: docker run --network container:minecraft1_minecraft_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:10001/
      - name: Test RCON web interface
        run: docker run --network container:minecraft1_rcon_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:11001/
