name: Test building the server with docker compose
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create the folders
        run: mkdir /home/runner/mcserver
      - run: mkdir /home/runner/rcon
      - name: Build the stack
        run: docker-compose up -d
